/**
 * GENERATED by scripts/translate-museums.mjs — DO NOT EDIT BY HAND.
 *
 * Stub initial version (empty record). Beka runs
 * `node scripts/translate-museums.mjs` once with GOOGLE_TRANSLATE_KEY
 * set; the script overwrites this file with the full pre-translated
 * data. Until then, `getMuseumStrings` falls back to the English
 * baseline in `topMuseums.ts`.
 */

export type MuseumTranslation = {
  name: string;
  blurb: string;
  city: string;
  country: string;
};

export const MUSEUM_TRANSLATIONS: Record<string, Record<string, MuseumTranslation>> = {};
