/**
 * GENERATED by scripts/translate-museums.mjs — DO NOT EDIT BY HAND.
 *
 * Pre-translated museum data baked at build time so the runtime
 * never has to call /api/translate for these strings. Re-run the
 * script after editing topMuseums.ts:
 *   node scripts/translate-museums.mjs
 *
 * The English baseline lives in topMuseums.ts; this file holds the
 * locale overlays. Consumer: getMuseumStrings(museum, lang) in
 * src/lib/museumTranslations.ts (hand-written wrapper).
 *
 * Engine: Gemini Flash 2.0 (see scripts/translate-museums.mjs for
 * the system prompt that ensures Georgia/Florence/Vatican City are
 * disambiguated correctly).
 */

export type MuseumTranslation = {
  name: string;
  blurb: string;
  city: string;
  country: string;
};

export const MUSEUM_TRANSLATIONS: Record<string, Record<string, MuseumTranslation>> = {
  "ar": null,
  "bn": null,
  "cs": null,
  "da": null,
  "de": null,
  "el": null,
  "es": null,
  "fa": null,
  "fi": null,
  "fr": null,
  "he": null,
  "hi": null,
  "hu": null,
  "id": null,
  "it": null,
  "ja": null,
  "ka": null,
  "ko": null,
  "ms": null,
  "nb": null,
  "nl": null,
  "pl": null,
  "pt-br": null,
  "pt-pt": null,
  "ro": null,
  "ru": null,
  "sv": null,
  "th": null,
  "tr": null,
  "uk": null,
  "ur": null,
  "vi": null,
  "zh-cn": null,
  "zh-tw": null
};
