/**
 * UNESCO World Heritage matcher.
 *
 * Strategy: a curated list of ~350 high-traffic UNESCO sites covering
 * basically every major destination Lokali users will ever search.
 * The full UNESCO list is ~1200 entries, but the long tail (rural
 * sites in Mongolia, archaeological digs in central Africa) doesn't
 * matter for our top-25 tourist cities and their neighbours.
 *
 * Matching: case-insensitive substring on `attractionName` plus
 * optional `city / type / description` context. We also short-circuit
 * to true if the haystack literally contains "unesco" — useful when
 * Claude / n8n explicitly mention UNESCO status in a description.
 *
 * Language-agnostic: the matcher only ever sees the English baseline
 * (smart cache always stores attractions in English, then translates
 * for display). The badge label itself is translated via i18n
 * (`unesco.title` / `unesco.short`), so users in any locale see the
 * pill in their language without changing this list.
 *
 * Decision cache: results are memoised in localStorage so the next
 * page load doesn't re-walk 350 needles for every attraction we
 * already evaluated.
 */

const UNESCO_SITES: string[] = [
  // ─── Italy
  "Colosseum",
  "Roman Forum",
  "Palatine Hill",
  "Vatican City",
  "St. Peter's Basilica",
  "St Peter's Basilica",
  "Sistine Chapel",
  "Pantheon",
  "Castel Sant'Angelo",
  "Historic Centre of Rome",
  "Trevi Fountain",
  "Spanish Steps",
  "Historic Centre of Florence",
  "Florence Cathedral",
  "Duomo di Firenze",
  "Ponte Vecchio",
  "Uffizi Gallery",
  "Pitti Palace",
  "Palazzo Vecchio",
  "Boboli Gardens",
  "Venice and its Lagoon",
  "St Mark's Basilica",
  "St. Mark's Basilica",
  "Doge's Palace",
  "Piazza San Marco",
  "Rialto Bridge",
  "Murano",
  "Burano",
  "Pisa Cathedral",
  "Leaning Tower of Pisa",
  "Piazza dei Miracoli",
  "Pompeii",
  "Herculaneum",
  "Cinque Terre",
  "Amalfi Coast",
  "Costiera Amalfitana",
  "Mount Etna",
  "Aeolian Islands",
  "Val d'Orcia",
  "Sassi di Matera",
  "Matera",
  "San Gimignano",
  "Siena Historic Centre",
  "Verona",
  "Ravenna",
  "Naples Historic Centre",
  "Genoa",
  "Urbino",
  "Mantua",
  "Sabbioneta",
  "Vicenza",
  "Padua",
  "Crespi d'Adda",
  "Hadrian's Villa",
  "Villa d'Este",
  "Su Nuraxi di Barumini",
  "Castel del Monte",
  "Trulli of Alberobello",
  "Aquileia",
  "Modena Cathedral",
  "Piazza Grande Modena",

  // ─── France
  "Banks of the Seine",
  "Notre-Dame de Paris",
  "Notre Dame Cathedral",
  "Louvre",
  "Sainte-Chapelle",
  "Conciergerie",
  "Palace of Versailles",
  "Mont-Saint-Michel",
  "Mont Saint-Michel",
  "Chartres Cathedral",
  "Carcassonne",
  "Pont du Gard",
  "Palais des Papes",
  "Pont d'Avignon",
  "Avignon Historic Centre",
  "Lyon Historic Site",
  "Strasbourg Grande Île",
  "Reims Cathedral",
  "Amiens Cathedral",
  "Bourges Cathedral",
  "Bordeaux Port of the Moon",
  "Saint-Émilion",
  "Loire Valley",
  "Château de Chambord",
  "Château de Chenonceau",
  "Vézelay",
  "Fontainebleau",
  "Provins",
  "Le Havre",
  "Albi Episcopal City",
  "Nîmes",
  "Arles Roman Monuments",
  "Théâtre Antique d'Orange",
  "Causses and the Cévennes",
  "Pyrénées-Mont Perdu",

  // ─── Spain
  "Alhambra",
  "Generalife",
  "Albayzín",
  "Sagrada Familia",
  "Sagrada Família",
  "Park Güell",
  "Park Guell",
  "Casa Batlló",
  "Casa Milà",
  "Casa Mila",
  "La Pedrera",
  "Palau de la Música Catalana",
  "Hospital de Sant Pau",
  "Works of Antoni Gaudí",
  "Casa Vicens",
  "Palau Güell",
  "Casa de los Botines",
  "El Escorial",
  "Aranjuez Cultural Landscape",
  "Toledo Historic City",
  "Segovia Aqueduct",
  "Segovia Old Town",
  "Alcázar of Seville",
  "Alcazar of Seville",
  "Seville Cathedral",
  "Giralda",
  "General Archive of the Indies",
  "Mosque-Cathedral of Córdoba",
  "Mezquita",
  "Historic Centre of Córdoba",
  "Avila",
  "Salamanca Old City",
  "Santiago de Compostela",
  "Cathedral of Santiago de Compostela",
  "Burgos Cathedral",
  "Las Médulas",
  "Doñana National Park",
  "Garajonay",
  "Teide National Park",
  "Ibiza",
  "San Cristóbal de La Laguna",
  "Cuenca Historic Walled Town",
  "Cáceres Old Town",
  "Antequera Dolmens",
  "Risco Caído",
  "Caves of Altamira",

  // ─── United Kingdom + Ireland
  "Tower of London",
  "Westminster Abbey",
  "Palace of Westminster",
  "Maritime Greenwich",
  "Royal Observatory Greenwich",
  "Cutty Sark",
  "Kew Gardens",
  "Royal Botanic Gardens, Kew",
  "Stonehenge",
  "Avebury",
  "Bath Roman",
  "City of Bath",
  "Edinburgh Old Town",
  "Edinburgh New Town",
  "Edinburgh Castle",
  "Hadrian's Wall",
  "Antonine Wall",
  "Giant's Causeway",
  "Blaenavon",
  "Pontcysyllte Aqueduct",
  "Liverpool Maritime Mercantile",
  "Derwent Valley Mills",
  "New Lanark",
  "Saltaire",
  "Ironbridge Gorge",
  "Studley Royal Park",
  "Fountains Abbey",
  "Durham Castle",
  "Durham Cathedral",
  "Canterbury Cathedral",
  "Forth Bridge",
  "Jurassic Coast",
  "Dorset and East Devon Coast",
  "Skellig Michael",
  "Brú na Bóinne",
  "Newgrange",

  // ─── Greece + Cyprus
  "Acropolis",
  "Parthenon",
  "Erechtheion",
  "Temple of Olympian Zeus",
  "Ancient Agora of Athens",
  "Delphi",
  "Olympia",
  "Mycenae",
  "Tiryns",
  "Mystras",
  "Mount Athos",
  "Meteora",
  "Knossos",
  "Heraklion Archaeological",
  "Rhodes Old Town",
  "Patmos",
  "Monastery of St John the Theologian",
  "Cave of the Apocalypse",
  "Daphni",
  "Hosios Loukas",
  "Nea Moni of Chios",
  "Vergina",
  "Pythagoreion",
  "Heraion of Samos",
  "Bassae",
  "Paphos",
  "Choirokoitia",

  // ─── Turkey
  "Hagia Sophia",
  "Blue Mosque",
  "Sultan Ahmed Mosque",
  "Topkapi Palace",
  "Topkapı Palace",
  "Basilica Cistern",
  "Suleymaniye Mosque",
  "Süleymaniye Mosque",
  "Historic Areas of Istanbul",
  "Cappadocia",
  "Göreme",
  "Goreme",
  "Ephesus",
  "Pamukkale",
  "Hierapolis",
  "Troy Archaeological",
  "Pergamon",
  "Aphrodisias",
  "Xanthos",
  "Letoon",
  "Hattusha",
  "Nemrut Dağ",
  "Mount Nemrut",
  "Diyarbakır Fortress",
  "Hevsel Gardens",
  "Bursa",
  "Cumalıkızık",
  "Safranbolu",
  "Edirne Selimiye Mosque",
  "Çatalhöyük",
  "Catalhoyuk",
  "Ani",
  "Göbekli Tepe",
  "Gobekli Tepe",
  "Aslantepe Mound",

  // ─── Czech Republic / Austria / Germany / Switzerland / Netherlands
  "Historic Centre of Prague",
  "Prague Castle",
  "Charles Bridge",
  "Český Krumlov",
  "Cesky Krumlov",
  "Kutná Hora",
  "Sedlec Ossuary",
  "Telč",
  "Lednice-Valtice",
  "Brno Tugendhat",
  "Olomouc Holy Trinity Column",
  "Karlovy Vary",
  "Mariánské Lázně",
  "Historic Centre of Vienna",
  "Schönbrunn Palace",
  "Schloss Schönbrunn",
  "Hofburg",
  "Belvedere Palace",
  "Salzburg Old Town",
  "Hallstatt",
  "Wachau Cultural Landscape",
  "Semmering Railway",
  "Graz Historic Centre",
  "Schloss Eggenberg",
  "Museum Island",
  "Cologne Cathedral",
  "Brandenburg Gate",
  "Speicherstadt",
  "Aachen Cathedral",
  "Würzburg Residence",
  "Bavarian Court Garden",
  "Wieskirche",
  "Hildesheim",
  "Lübeck Hanseatic",
  "Wartburg",
  "Bauhaus",
  "Wittenberg",
  "Bamberg Town",
  "Quedlinburg",
  "Trier Roman",
  "Porta Nigra",
  "Maulbronn Monastery",
  "Reichenau",
  "Messel Pit",
  "Zollverein Coal Mine",
  "Berlin Modernism Housing",
  "Castles of Augustusburg",
  "Limes",
  "Naumburg Cathedral",
  "Bergpark Wilhelmshöhe",
  "Pillnitz",
  "Pilatus",
  "Old City of Bern",
  "Abbey of St Gall",
  "Convent of Saint Gall",
  "Castles of Bellinzona",
  "Lavaux Vineyard",
  "Rhaetian Railway",
  "Jungfrau-Aletsch",
  "Sardona Tectonic Arena",
  "Le Corbusier",
  "Canal Ring",
  "Singel",
  "Kinderdijk",
  "Beemster",
  "Schokland",
  "Ir. D.F. Woudagemaal",
  "Stelling van Amsterdam",
  "Rietveld Schröder House",
  "Van Nellefabriek",

  // ─── Portugal
  "Tower of Belém",
  "Torre de Belém",
  "Jerónimos Monastery",
  "Mosteiro dos Jerónimos",
  "Sintra Cultural Landscape",
  "Pena Palace",
  "Quinta da Regaleira",
  "Castle of the Moors",
  "Alto Douro Wine Region",
  "Pico Island Vineyard",
  "Madeira Laurisilva",
  "Évora Historic Centre",
  "Porto Historic Centre",
  "Ribeira Porto",
  "Coimbra University",
  "Tomar Convent of Christ",
  "Alcobaça Monastery",
  "Batalha Monastery",
  "Elvas Garrison",
  "Mafra Royal Building",
  "Côa Valley",
  "Guimarães",

  // ─── Morocco / Egypt / Levant / Iran / Gulf
  "Medina of Marrakech",
  "Koutoubia Mosque",
  "Bahia Palace",
  "Jemaa el-Fnaa",
  "Medina of Fes",
  "Medina of Fez",
  "Volubilis",
  "Medina of Tetouan",
  "Medina of Essaouira",
  "Ksar of Ait-Ben-Haddou",
  "Aït Benhaddou",
  "Meknes Historic City",
  "Portuguese City of Mazagan",
  "Rabat",
  "Pyramids of Giza",
  "Great Pyramid",
  "Sphinx",
  "Memphis Egypt",
  "Saqqara",
  "Step Pyramid",
  "Historic Cairo",
  "Khan el-Khalili",
  "Al-Azhar Mosque",
  "Sultan Hassan",
  "Citadel of Cairo",
  "Abu Simbel",
  "Karnak",
  "Luxor Temple",
  "Valley of the Kings",
  "Hatshepsut Temple",
  "Saint Catherine's Monastery",
  "Mount Sinai",
  "Petra",
  "Wadi Rum",
  "Old City of Jerusalem",
  "Western Wall",
  "Dome of the Rock",
  "Holy Sepulchre",
  "Bethlehem Church of the Nativity",
  "Masada",
  "Akko",
  "Baha'i",
  "Bahá'í",
  "Persepolis",
  "Naqsh-e Jahan Square",
  "Shah Mosque",
  "Pasargadae",
  "Tchogha Zanbil",
  "Soltaniyeh",
  "Bam Citadel",
  "Yazd",
  "Susa",
  "Babylon",
  "Hatra",
  "Samarra",
  "Erbil Citadel",
  "Palmyra",
  "Bosra",
  "Crac des Chevaliers",
  "Old City of Sana'a",
  "Shibam",
  "Al Ain",
  "Hegra",
  "Mada'in Saleh",
  "Diriyah",

  // ─── South / South-East / East Asia
  "Singapore Botanic Gardens",
  "Cultural Landscape of Bali",
  "Subak System",
  "Tanah Lot",
  "Borobudur",
  "Prambanan",
  "Ujung Kulon",
  "Komodo National Park",
  "Lorentz",
  "Sangiran",
  "Angkor Wat",
  "Angkor Thom",
  "Bayon",
  "Ta Prohm",
  "Banteay Srei",
  "Preah Vihear",
  "Sukhothai",
  "Ayutthaya",
  "Dong Phayayen",
  "Si Thep",
  "Hạ Long Bay",
  "Halong Bay",
  "Hoi An",
  "Hue Imperial",
  "My Son",
  "Phong Nha",
  "Trang An",
  "Great Wall of China",
  "Forbidden City",
  "Imperial Palaces of Beijing",
  "Summer Palace",
  "Temple of Heaven",
  "Ming Tombs",
  "Terracotta Army",
  "Mausoleum of the First Qin Emperor",
  "Mogao Caves",
  "Mount Wutai",
  "Mount Tai",
  "Mount Huangshan",
  "Huangshan",
  "Mount Wuyi",
  "Mount Emei",
  "Leshan Giant Buddha",
  "Potala Palace",
  "Jokhang Temple",
  "Lhasa",
  "Macau Historic Centre",
  "Lijiang Old Town",
  "Pingyao Ancient City",
  "Suzhou Classical Gardens",
  "Hangzhou West Lake",
  "Dazu Rock Carvings",
  "Longmen Grottoes",
  "Yungang Grottoes",
  "Kulangsu",
  "Quanzhou",
  "Kaiping Diaolou",
  "Fujian Tulou",
  "Three Parallel Rivers",
  "Wulingyuan",
  "Jiuzhaigou",
  "Huanglong",
  "Sichuan Giant Panda",
  "Zhangjiajie",
  "Kyoto Historic Monuments",
  "Kiyomizu-dera",
  "Kinkaku-ji",
  "Ginkaku-ji",
  "Ryōan-ji",
  "Ryoan-ji",
  "Nijo Castle",
  "Nara Historic Monuments",
  "Tōdai-ji",
  "Todai-ji",
  "Kasuga Taisha",
  "Hōryū-ji",
  "Horyu-ji",
  "Himeji Castle",
  "Itsukushima Shrine",
  "Miyajima",
  "Mount Fuji",
  "Hiroshima Peace Memorial",
  "Genbaku Dome",
  "Atomic Bomb Dome",
  "Shirakawa-go",
  "Gokayama",
  "Yakushima",
  "Shiretoko",
  "Ogasawara",
  "Hiraizumi",
  "Tomioka Silk Mill",
  "Meiji Industrial Revolution",
  "Mozu-Furuichi Kofun",
  "Amami Ōshima",
  "Iwami Ginzan",
  "Ryūkyū",
  "Hahoe",
  "Yangdong",
  "Bulguksa",
  "Seokguram",
  "Jongmyo Shrine",
  "Changdeokgung",
  "Hwaseong Fortress",
  "Tripitaka Koreana",
  "Haeinsa",
  "Jeju Volcanic",
  "Gyeongju Historic Areas",
  "Royal Tombs Joseon",
  "Baekje Historic Areas",
  "Sansa Buddhist Mountain",
  "Seowon",
  "Getbol",
  "Taj Mahal",
  "Red Fort",
  "Qutub Minar",
  "Humayun's Tomb",
  "Khajuraho",
  "Hampi",
  "Ajanta Caves",
  "Ellora Caves",
  "Sundarbans",
  "Western Ghats",
  "Konark Sun Temple",
  "Mahabalipuram",
  "Group of Monuments at Mahabalipuram",
  "Great Living Chola Temples",
  "Brihadeeswarar",
  "Pattadakal",
  "Hampi Group",
  "Fatehpur Sikri",
  "Agra Fort",
  "Champaner-Pavagadh",
  "Bodh Gaya",
  "Mahabodhi",
  "Chhatrapati Shivaji Terminus",
  "Mountain Railways of India",
  "Darjeeling Himalayan",
  "Nilgiri Mountain",
  "Le Corbusier Chandigarh",
  "Rani-ki-Vav",
  "Stepwell at Patan",
  "Kaziranga",
  "Keoladeo",
  "Manas",
  "Nanda Devi",
  "Khangchendzonga",
  "Jaipur",
  "Hawa Mahal",
  "Jantar Mantar",
  "Lumbini",
  "Sagarmatha",
  "Chitwan",
  "Kathmandu Valley",
  "Pashupatinath",
  "Boudhanath",
  "Bagan",
  "Pyu Ancient Cities",
  "Sigiriya",
  "Anuradhapura",
  "Polonnaruwa",
  "Dambulla",
  "Kandy",
  "Sinharaja",
  "Galle Fort",
  "Mahaweli",

  // ─── North America
  "Statue of Liberty",
  "Independence Hall",
  "Mesa Verde",
  "Yellowstone",
  "Yosemite",
  "Grand Canyon",
  "Everglades",
  "Mammoth Cave",
  "Olympic National Park",
  "Redwood",
  "Carlsbad Caverns",
  "Great Smoky Mountains",
  "Hawaii Volcanoes",
  "Glacier Bay",
  "Wrangell-St. Elias",
  "Kluane",
  "Cahokia Mounds",
  "Chaco Culture",
  "Taos Pueblo",
  "Monticello",
  "University of Virginia",
  "San Antonio Missions",
  "Poverty Point",
  "Frank Lloyd Wright",
  "Hopewell Ceremonial",
  "Old Quebec",
  "Lunenburg",
  "L'Anse aux Meadows",
  "Banff National Park",
  "Jasper",
  "Canadian Rocky Mountain",
  "Gros Morne",
  "Dinosaur Provincial Park",
  "Head-Smashed-In Buffalo Jump",
  "Wood Buffalo",
  "Nahanni",
  "SGang Gwaay",
  "Rideau Canal",
  "Mistaken Point",
  "Pimachiowin Aki",

  // ─── Latin America
  "Machu Picchu",
  "Cusco Old City",
  "Sacred Valley",
  "Nazca Lines",
  "Chan Chan",
  "Chavin",
  "Manú National Park",
  "Río Abiseo",
  "Huascarán",
  "Lima Historic Centre",
  "Arequipa Historic Centre",
  "Chichen Itza",
  "Chichén Itzá",
  "Teotihuacan",
  "Palenque",
  "Tikal",
  "Tulum",
  "Uxmal",
  "Calakmul",
  "El Tajín",
  "Monte Albán",
  "Oaxaca Historic Centre",
  "Puebla Historic Centre",
  "Mexico City Historic Centre",
  "Xochimilco",
  "Guanajuato",
  "Morelia Historic Centre",
  "Zacatecas Historic Centre",
  "Querétaro Historic Centre",
  "San Miguel de Allende",
  "Campeche",
  "Tlacotalpan",
  "Sian Ka'an",
  "El Pinacate",
  "Whale Sanctuary of El Vizcaino",
  "Iguazu",
  "Iguaçu",
  "Galápagos",
  "Galapagos",
  "Easter Island",
  "Rapa Nui",
  "Christ the Redeemer",
  "Sugarloaf Mountain",
  "Cartagena Port",
  "Quito Old Town",
  "Ouro Preto",
  "Salvador da Bahia",
  "Olinda",
  "Brasília",
  "Brasilia",
  "Pantanal",
  "Atlantic Forest",
  "Pampulha",
  "Cuenca Historic",
  "La Habana Vieja",
  "Old Havana",
  "Trinidad Cuba",
  "Antigua Guatemala",
  "Panama Viejo",
  "Casco Viejo Panama",
  "Coro",
  "Valparaíso",
  "Sewell Mining Town",
  "Hospicio Cabañas",
  "Tequila",
  "Sucre Historic City",
  "Potosí",
  "Tiwanaku",
  "Noel Kempff Mercado",

  // ─── Russia / Caucasus / Eastern Europe
  "Moscow Kremlin",
  "Red Square",
  "St. Basil's Cathedral",
  "Saint Basil's Cathedral",
  "Hermitage",
  "Historic Centre of Saint Petersburg",
  "Peterhof",
  "Tsarskoye Selo",
  "Catherine Palace",
  "Lake Baikal",
  "Kizhi Pogost",
  "Trinity Sergius Lavra",
  "Solovetsky Islands",
  "Novodevichy Convent",
  "Yaroslavl Historical",
  "Suzdal",
  "Vladimir",
  "Ferapontov",
  "Volcanoes of Kamchatka",
  "Golden Mountains of Altai",
  "Western Caucasus",
  "Curonian Spit",
  "Mtskheta",
  "Jvari Monastery",
  "Svetitskhoveli",
  "Gelati Monastery",
  "Bagrati Cathedral",
  "Upper Svaneti",
  "Echmiadzin",
  "Geghard",
  "Khor Virap",
  "Haghpat",
  "Sanahin",
  "Zvartnots",
  "Gobustan",
  "Walled City of Baku",
  "Maiden Tower",
  "Shirvanshahs Palace",
  "Wieliczka Salt Mine",
  "Auschwitz Birkenau",
  "Auschwitz-Birkenau",
  "Old Town of Krakow",
  "Old Town of Warsaw",
  "Wrocław Centennial Hall",
  "Białowieża",
  "Bran Castle",
  "Painted Churches of Moldavia",
  "Wooden Churches of Maramureș",
  "Sighișoara",
  "Sibiu",
  "Dacian Fortresses",
  "Danube Delta",
  "Dubrovnik Old Town",
  "Plitvice Lakes",
  "Diocletian's Palace",
  "Stari Grad Plain",
  "Stećci",
  "Stari Most",
  "Mostar",
  "Old Town of Korčula",
  "Trogir",
  "Šibenik",
  "Sibenik",
  "Episcopal Complex of Poreč",
  "Saint Sophia Sofia",
  "Boyana Church",
  "Rila Monastery",
  "Ancient City of Nessebar",
  "Madara Rider",
  "Pirin",
  "Belogradchik",
  "Studenica Monastery",
  "Stari Ras",
  "Sopoćani",
  "Gamzigrad",
  "Felix Romuliana",
  "Ohrid",
  "Lake Ohrid",
  "Berat Historic Centre",
  "Gjirokastër",

  // ─── Scandinavia / Baltics / Iberia outskirts
  "Bryggen",
  "Geirangerfjord",
  "Nærøyfjord",
  "Naroyfjord",
  "West Norwegian Fjords",
  "Urnes Stave Church",
  "Røros Mining Town",
  "Vegaøyan",
  "Rock Carvings at Alta",
  "Drottningholm Palace",
  "Birka",
  "Tanum Rock Carvings",
  "Skogskyrkogården",
  "Visby",
  "Hanseatic Town of Visby",
  "Engelsberg Ironworks",
  "Hammurabi",
  "Suomenlinna",
  "Old Rauma",
  "Verla",
  "Petäjävesi",
  "Sammallahdenmäki",
  "Kvarken",
  "High Coast",
  "Christiansfeld",
  "Kronborg",
  "Roskilde Cathedral",
  "Jelling Mounds",
  "Wadden Sea",
  "Kuršių Nerija",
  "Vilnius Historic Centre",
  "Kernavė",
  "Riga Historic Centre",
  "Struve Geodetic Arc",
  "Tallinn Historic Centre",
  "Old Town of Tallinn",

  // ─── Africa (Sub-Saharan + remainder of north)
  "Robben Island",
  "Cape Floral Region",
  "Cradle of Humankind",
  "Mapungubwe",
  "iSimangaliso",
  "Drakensberg",
  "uKhahlamba",
  "Vredefort Dome",
  "Khami Ruins",
  "Great Zimbabwe",
  "Mana Pools",
  "Matobo Hills",
  "Serengeti",
  "Ngorongoro",
  "Kilimanjaro",
  "Stone Town of Zanzibar",
  "Kondoa Rock-Art",
  "Lalibela",
  "Aksum",
  "Fasil Ghebbi",
  "Gondar",
  "Lower Valley of the Awash",
  "Tiya",
  "Konso",
  "Harar Jugol",
  "Simien",
  "Bale Mountains",
  "Victoria Falls",
  "Mosi-oa-Tunya",
  "Okavango Delta",
  "Tsodilo",
  "Twyfelfontein",
  "Namib Sand Sea",
  "Bwindi Impenetrable",
  "Rwenzori",
  "Kasubi Tombs",
  "Kibale",
  "Murchison Falls",
  "Salonga",
  "Kahuzi-Biega",
  "Garamba",
  "Virunga",
  "Lopé-Okanda",
  "Dja Faunal Reserve",
  "Sangha Trinational",
  "Bandiagara",
  "Djenné",
  "Timbuktu",
  "Gao",
  "Tombs of Buganda Kings",
  "Mt. Kenya",
  "Lake Turkana",
  "Lamu Old Town",
  "Mijikenda Kaya Forests",
  "Fort Jesus",
  "Maloti-Drakensberg",
  "Île de Gorée",
  "Saint-Louis Senegal",
  "Bassari Country",
  "Niokolo-Koba",
  "Sine-Saloum",
  "James Island",
  "Stone Circles of Senegambia",
  "Aapravasi Ghat",
  "Le Morne",
  "Tsingy de Bemaraha",
  "Royal Hill of Ambohimanga",
  "Rainforests of the Atsinanana",
  "Aldabra Atoll",
  "Vallée de Mai",
  "Maropeng",
  "Sukur",
  "Osun-Osogbo",

  // ─── Australia / Oceania
  "Sydney Opera House",
  "Great Barrier Reef",
  "Uluru",
  "Kakadu",
  "Daintree",
  "Wet Tropics of Queensland",
  "Tasmanian Wilderness",
  "Blue Mountains",
  "Lord Howe",
  "Shark Bay",
  "Fraser Island",
  "K'gari",
  "Greater Blue Mountains",
  "Royal Exhibition Building",
  "Carlton Gardens",
  "Cockatoo Island",
  "Australian Convict Sites",
  "Ningaloo Coast",
  "Macquarie Island",
  "Heard and McDonald",
  "Tongariro",
  "Te Wahipounamu",
  "Sub-Antarctic Islands",
  "Phoenix Islands",
  "East Rennell",
];

const UNESCO_NEEDLES = UNESCO_SITES.map((s) => s.toLowerCase()).filter((s) => s.length >= 8);

/* ─── localStorage memo ─── */

const MEMO_KEY = "unesco:memo:v1";
const MEMO_TTL_MS = 1000 * 60 * 60 * 24 * 90; // 90 days
type MemoFile = Record<string, { v: boolean; t: number }>;

function readMemo(): MemoFile {
  if (typeof window === "undefined") return {};
  try {
    const raw = window.localStorage.getItem(MEMO_KEY);
    return raw ? (JSON.parse(raw) as MemoFile) : {};
  } catch {
    return {};
  }
}

function writeMemo(memo: MemoFile): void {
  if (typeof window === "undefined") return;
  try {
    window.localStorage.setItem(MEMO_KEY, JSON.stringify(memo));
  } catch {
    /* quota / private mode — ignore */
  }
}

function memoLookup(key: string): boolean | undefined {
  const memo = readMemo();
  const entry = memo[key];
  if (!entry) return undefined;
  if (Date.now() - entry.t > MEMO_TTL_MS) return undefined;
  return entry.v;
}

function memoStore(key: string, value: boolean): void {
  const memo = readMemo();
  // Prevent unbounded growth — drop the oldest 50% once we hit 5000 keys.
  const keys = Object.keys(memo);
  if (keys.length >= 5000) {
    const sorted = keys.sort((a, b) => memo[a].t - memo[b].t).slice(0, Math.floor(keys.length / 2));
    for (const k of sorted) delete memo[k];
  }
  memo[key] = { v: value, t: Date.now() };
  writeMemo(memo);
}

/**
 * Heuristic: returns true if `attractionName` (or the optional
 * city / type / description fields) matches a UNESCO World Heritage
 * site. Result is cached in localStorage for 90 days so repeat
 * lookups (a long results page, a re-render) don't re-scan the
 * 350-entry needle list every time.
 */
export function isUnescoSite(
  attractionName: string | null | undefined,
  context?: { city?: string | null; type?: string | null; description?: string | null },
): boolean {
  if (!attractionName) return false;

  const memoKey = [
    attractionName,
    context?.city ?? "",
    context?.type ?? "",
    // Description is volatile — hash it down to a length so we don't
    // bust the memo on every re-translation; same lengths almost
    // always mean same content for our purposes.
    String(context?.description?.length ?? 0),
  ]
    .join("|")
    .toLowerCase();

  const cached = memoLookup(memoKey);
  if (cached !== undefined) return cached;

  const haystack = [
    attractionName,
    context?.city ?? "",
    context?.type ?? "",
    context?.description ?? "",
  ]
    .join(" ")
    .toLowerCase();

  let result = false;
  if (haystack.includes("unesco") || haystack.includes("world heritage")) {
    result = true;
  } else {
    for (const needle of UNESCO_NEEDLES) {
      if (haystack.includes(needle)) {
        result = true;
        break;
      }
    }
  }

  memoStore(memoKey, result);
  return result;
}
