import { createFileRoute } from "@tanstack/react-router";
import { CORS_HEADERS, corsPreflight } from "@/lib/cors.server";
import { getCachedMuseumHighlights, putCachedMuseumHighlights } from "@/lib/sharedCache.server";
import { translateMuseumHighlightsPayload } from "@/lib/translatePayload.server";
import { callClaude, parseClaudeJson } from "@/lib/anthropic.server";
import { buildMuseumHighlightsSystem, buildMuseumHighlightsUser } from "@/lib/prompts";
import { MUSEUMS_BY_ID } from "@/lib/topMuseums";

/**
 * /api/museum-highlights — Cloudflare Worker route that returns the
 * "must-see top 30" payload for one museum, generated by Claude
 * Sonnet (quality matters here, same reasoning as the guide route)
 * and cached in Supabase per (museum_id, language).
 *
 * Request body: { museumId: string, language: string }
 * - museumId must match an id in src/lib/topMuseums.ts (e.g. "louvre",
 *   "british-museum"). Anything else returns an empty payload.
 * - language is a normalised lang code ("en", "ka", "es", "zh-cn", …).
 *
 * Cache strategy mirrors /api/guide:
 *   1. Direct hit on (museum_id, language).
 *   2. Miss + non-English → look up English baseline, translate.
 *   3. Miss everywhere → call Claude in English, cache, translate
 *      and cache the user-language row too.
 *
 * `X-Cache: HIT|TRANSLATED|MISS|MISS-TRANSLATED|MISS-NO-TRANS` for
 * monitoring.
 */
export const Route = createFileRoute("/api/museum-highlights")({
  server: {
    handlers: {
      OPTIONS: async () => corsPreflight(),
      POST: async ({ request }) => {
        const rawBody = await request.text();
        const key = extractKey(rawBody);
        if (!key) {
          return jsonResponse({ highlights: [] }, 200, "MISS", "no-museum");
        }
        const userLang = key.language;
        const wantsTranslation = !isEnglish(userLang);

        // 1. Direct cache hit.
        const cached = await getCachedMuseumHighlights({
          museumId: key.museumId,
          language: userLang,
        });
        if (cached !== null && hasHighlights(cached)) {
          return jsonResponse(cached, 200, "HIT");
        }

        // 2. Miss + non-English → English baseline + translate.
        if (wantsTranslation) {
          const cachedEn = await getCachedMuseumHighlights({
            museumId: key.museumId,
            language: "en",
          });
          if (cachedEn !== null && hasHighlights(cachedEn)) {
            const { payload: translated, translated: ok } = await translateMuseumHighlightsPayload(
              cachedEn,
              userLang,
            );
            if (ok)
              await putCachedMuseumHighlights(
                { museumId: key.museumId, language: userLang },
                translated,
              );
            return jsonResponse(translated, 200, ok ? "TRANSLATED" : "TRANSLATE-FAILED");
          }
        }

        // 3. Cache miss everywhere — call Claude in English.
        const museum = MUSEUMS_BY_ID.get(key.museumId);
        if (!museum) {
          return jsonResponse({ highlights: [] }, 200, "MISS", "unknown-museum");
        }
        try {
          const system = buildMuseumHighlightsSystem();
          const user = buildMuseumHighlightsUser({
            name: museum.name,
            city: museum.city,
            language: "en",
          });
          // Haiku, not Sonnet — Beka's first deploy hit Cloudflare's
          // 100 s origin timeout (524 Bad Gateway: "[anthropic] 524").
          // Sonnet at ~50 tok/s × 8192 maxTokens worst-cases past 2.5
          // minutes; the worker dies long before Anthropic finishes.
          // Haiku at ~150 tok/s brings the same 30-item payload into
          // a comfortable 25-40 s window. The list-shaped output (no
          // long narrated prose) reads the same on both models, so
          // there's no quality cost. Sonnet stays on /api/guide where
          // the multi-paragraph script genuinely benefits from it.
          // maxTokens dropped 8192 → 6144 to leave further headroom.
          const text = await callClaude({
            model: "claude-haiku-4-5",
            system,
            user,
            maxTokens: 6144,
          });
          const parsedRaw = parseClaudeJson(text);
          // Normalise so {items:[...]}, {data:{highlights:...}}, or
          // a bare [...] all become { highlights: [...] } before the
          // cache write — frontend can keep its single shape contract.
          const parsed = normaliseHighlights(parsedRaw);

          if (parsed !== undefined && hasHighlights(parsed)) {
            await putCachedMuseumHighlights({ museumId: key.museumId, language: "en" }, parsed);
          }

          if (parsed === undefined || !hasHighlights(parsed)) {
            // Surface as much detail as we can — Beka had to guess
            // why "No highlights yet" appeared. Logged to Lovable
            // Logs and echoed in the response body.
            const preview = typeof text === "string" ? text.slice(0, 200) : "(no text)";
            console.warn(
              "[museum-highlights] empty after parse",
              key.museumId,
              "preview:",
              preview,
            );
            return jsonResponse(
              { highlights: [], debug: { museum: museum.name, textPreview: preview } },
              200,
              "MISS",
              "upstream-empty",
            );
          }

          if (wantsTranslation) {
            const { payload: translated, translated: ok } = await translateMuseumHighlightsPayload(
              parsed,
              userLang,
            );
            if (ok)
              await putCachedMuseumHighlights(
                { museumId: key.museumId, language: userLang },
                translated,
              );
            return jsonResponse(translated, 200, ok ? "MISS-TRANSLATED" : "MISS-NO-TRANS");
          }

          return jsonResponse(parsed, 200, "MISS");
        } catch (err) {
          return new Response(
            JSON.stringify({
              highlights: [],
              error: err instanceof Error ? err.message : "Upstream failed",
            }),
            {
              status: 502,
              headers: { ...CORS_HEADERS, "Content-Type": "application/json" },
            },
          );
        }
      },
    },
  },
});

function extractKey(rawBody: string): { museumId: string; language: string } | null {
  try {
    const obj = JSON.parse(rawBody) as Record<string, unknown>;
    const museumId =
      (typeof obj.museumId === "string" && obj.museumId) ||
      (typeof obj.museum_id === "string" && obj.museum_id) ||
      "";
    const language =
      (typeof obj.language === "string" && obj.language) ||
      (typeof obj.lang === "string" && obj.lang) ||
      "en";
    if (!museumId.trim()) return null;
    return { museumId: museumId.trim().toLowerCase(), language: language.trim().toLowerCase() };
  } catch {
    return null;
  }
}

function isEnglish(lang: string): boolean {
  return !lang || lang.toLowerCase().startsWith("en");
}

function hasHighlights(payload: unknown): boolean {
  if (!payload || typeof payload !== "object") return false;
  // Tolerate the variant shapes Claude occasionally returns:
  //   { highlights: [...] }       — canonical
  //   { items: [...] }            — Claude sometimes renames the key
  //   { data: { highlights: ... } } — wrapper envelope
  //   [...]                       — bare array
  if (Array.isArray(payload)) return payload.length > 0;
  const obj = payload as Record<string, unknown>;
  const candidates = [obj.highlights, obj.items, obj.results, obj.list];
  for (const c of candidates) {
    if (Array.isArray(c) && c.length > 0) return true;
  }
  if (obj.data && typeof obj.data === "object") {
    return hasHighlights(obj.data);
  }
  return false;
}

/**
 * Normalise whatever Claude returned into the canonical
 * `{ highlights: [...] }` shape the frontend expects. Mirrors the
 * tolerance of hasHighlights — keeps cached payloads consistent
 * regardless of which variant key Claude used.
 */
function normaliseHighlights(payload: unknown): unknown {
  if (!payload || typeof payload !== "object") return payload;
  if (Array.isArray(payload)) return { highlights: payload };
  const obj = payload as Record<string, unknown>;
  if (Array.isArray(obj.highlights)) return obj;
  for (const key of ["items", "results", "list"] as const) {
    if (Array.isArray(obj[key])) return { highlights: obj[key] };
  }
  if (obj.data && typeof obj.data === "object") {
    return normaliseHighlights(obj.data);
  }
  return payload;
}

function jsonResponse(
  payload: unknown,
  status: number,
  cacheTag: string,
  reason?: string,
): Response {
  const headers: Record<string, string> = {
    ...CORS_HEADERS,
    "Content-Type": "application/json",
    "X-Cache": cacheTag,
  };
  if (reason) headers["X-Cache-Reason"] = reason;
  // Surface the reason inside the body too — Beka couldn't see
  // X-Cache-Reason from screenshots of the rendered card and had to
  // guess why "No highlights yet" appeared. Empty responses now ship
  // a `reason` field so the failure mode is visible in DevTools'
  // Response tab without checking headers.
  let body: string;
  if (typeof payload === "string") {
    body = payload;
  } else if (
    reason &&
    payload &&
    typeof payload === "object" &&
    !(payload as { reason?: unknown }).reason
  ) {
    body = JSON.stringify({ ...(payload as object), reason });
  } else {
    body = JSON.stringify(payload);
  }
  return new Response(body, { status, headers });
}
