import { createFileRoute } from "@tanstack/react-router";
import { getCachedMuseumHighlights, putCachedMuseumHighlights } from "@/lib/sharedCache.server";
import { translateMuseumHighlightsPayload } from "@/lib/translatePayload.server";
import { callClaude, parseClaudeJson } from "@/lib/anthropic.server";
import { buildMuseumHighlightsSystem, buildMuseumHighlightsUser } from "@/lib/prompts";
import { MUSEUMS_BY_ID } from "@/lib/topMuseums";

/**
 * /api/museum-highlights — Cloudflare Worker route that returns the
 * "must-see top 30" payload for one museum, generated by Claude
 * Sonnet (quality matters here, same reasoning as the guide route)
 * and cached in Supabase per (museum_id, language).
 *
 * Request body: { museumId: string, language: string }
 * - museumId must match an id in src/lib/topMuseums.ts (e.g. "louvre",
 *   "british-museum"). Anything else returns an empty payload.
 * - language is a normalised lang code ("en", "ka", "es", "zh-cn", …).
 *
 * Cache strategy mirrors /api/guide:
 *   1. Direct hit on (museum_id, language).
 *   2. Miss + non-English → look up English baseline, translate.
 *   3. Miss everywhere → call Claude in English, cache, translate
 *      and cache the user-language row too.
 *
 * `X-Cache: HIT|TRANSLATED|MISS|MISS-TRANSLATED|MISS-NO-TRANS` for
 * monitoring.
 */
export const Route = createFileRoute("/api/museum-highlights")({
  server: {
    handlers: {
      POST: async ({ request }) => {
        const rawBody = await request.text();
        const key = extractKey(rawBody);
        if (!key) {
          return jsonResponse({ highlights: [] }, 200, "MISS", "no-museum");
        }
        const userLang = key.language;
        const wantsTranslation = !isEnglish(userLang);

        // 1. Direct cache hit.
        const cached = await getCachedMuseumHighlights({
          museumId: key.museumId,
          language: userLang,
        });
        if (cached !== null && hasHighlights(cached)) {
          return jsonResponse(cached, 200, "HIT");
        }

        // 2. Miss + non-English → English baseline + translate.
        if (wantsTranslation) {
          const cachedEn = await getCachedMuseumHighlights({
            museumId: key.museumId,
            language: "en",
          });
          if (cachedEn !== null && hasHighlights(cachedEn)) {
            const { payload: translated, translated: ok } = await translateMuseumHighlightsPayload(
              cachedEn,
              userLang,
            );
            if (ok)
              await putCachedMuseumHighlights(
                { museumId: key.museumId, language: userLang },
                translated,
              );
            return jsonResponse(translated, 200, ok ? "TRANSLATED" : "TRANSLATE-FAILED");
          }
        }

        // 3. Cache miss everywhere — call Claude in English.
        const museum = MUSEUMS_BY_ID.get(key.museumId);
        if (!museum) {
          return jsonResponse({ highlights: [] }, 200, "MISS", "unknown-museum");
        }
        try {
          const system = buildMuseumHighlightsSystem();
          const user = buildMuseumHighlightsUser({
            name: museum.name,
            city: museum.city,
            language: "en",
          });
          // Sonnet, not Haiku — matches /api/guide's reasoning.
          // Highlights are the "must-see canon" of a major museum, the
          // copy needs to feel like a curator wrote it. Worth the
          // 30-60 s per (museum, language) since it caches forever.
          // Big maxTokens because 30 highlights × ~110-word stories is
          // 3.3k words ≈ 4.4k tokens output, plus brief / era / hint
          // overhead — 8192 leaves comfortable headroom.
          const text = await callClaude({
            system,
            user,
            maxTokens: 8192,
          });
          const parsed = parseClaudeJson(text);

          if (parsed !== undefined && hasHighlights(parsed)) {
            await putCachedMuseumHighlights({ museumId: key.museumId, language: "en" }, parsed);
          }

          if (parsed === undefined || !hasHighlights(parsed)) {
            return jsonResponse({ highlights: [] }, 200, "MISS", "upstream-empty");
          }

          if (wantsTranslation) {
            const { payload: translated, translated: ok } = await translateMuseumHighlightsPayload(
              parsed,
              userLang,
            );
            if (ok)
              await putCachedMuseumHighlights(
                { museumId: key.museumId, language: userLang },
                translated,
              );
            return jsonResponse(translated, 200, ok ? "MISS-TRANSLATED" : "MISS-NO-TRANS");
          }

          return jsonResponse(parsed, 200, "MISS");
        } catch (err) {
          return new Response(
            JSON.stringify({
              highlights: [],
              error: err instanceof Error ? err.message : "Upstream failed",
            }),
            { status: 502, headers: { "Content-Type": "application/json" } },
          );
        }
      },
    },
  },
});

function extractKey(rawBody: string): { museumId: string; language: string } | null {
  try {
    const obj = JSON.parse(rawBody) as Record<string, unknown>;
    const museumId =
      (typeof obj.museumId === "string" && obj.museumId) ||
      (typeof obj.museum_id === "string" && obj.museum_id) ||
      "";
    const language =
      (typeof obj.language === "string" && obj.language) ||
      (typeof obj.lang === "string" && obj.lang) ||
      "en";
    if (!museumId.trim()) return null;
    return { museumId: museumId.trim().toLowerCase(), language: language.trim().toLowerCase() };
  } catch {
    return null;
  }
}

function isEnglish(lang: string): boolean {
  return !lang || lang.toLowerCase().startsWith("en");
}

function hasHighlights(payload: unknown): boolean {
  if (!payload || typeof payload !== "object") return false;
  const arr = (payload as { highlights?: unknown }).highlights;
  return Array.isArray(arr) && arr.length > 0;
}

function jsonResponse(
  payload: unknown,
  status: number,
  cacheTag: string,
  reason?: string,
): Response {
  const headers: Record<string, string> = {
    "Content-Type": "application/json",
    "X-Cache": cacheTag,
  };
  if (reason) headers["X-Cache-Reason"] = reason;
  return new Response(JSON.stringify(payload), { status, headers });
}
