import { createFileRoute } from "@tanstack/react-router";
import { getCachedTimeMachine, putCachedTimeMachine } from "@/lib/sharedCache.server";
import { translateTimeMachinePayload } from "@/lib/translatePayload.server";
import { callClaude, parseClaudeJson } from "@/lib/anthropic.server";
import { buildTimeMachineSystem, buildTimeMachineUser } from "@/lib/prompts";
import { ATTRACTIONS_BY_ID, TIME_MACHINE_ROLES } from "@/lib/timeMachineData";

/**
 * /api/time-machine — Cloudflare Worker route that returns the
 * immersive first-person simulation for one (moment, role, language)
 * triple, generated by Claude Haiku 4.5 and cached in Supabase.
 *
 * Request body: { attractionId: string, role: string, language: string }
 *   - attractionId  → must match an id in src/lib/timeMachineData.ts
 *                     ATTRACTIONS (e.g. "pompeii_day", "bastille",
 *                     "baghdad_mongols"). Anything else returns 400.
 *   - role          → one of TIME_MACHINE_ROLES (merchant, soldier, …).
 *   - language      → normalised lang code ("en", "ka", "es", …).
 *
 * Cache strategy mirrors /api/museum-highlights:
 *   1. Direct hit on (attraction_id, role, language).
 *   2. Miss + non-English → look up the English baseline for the same
 *      (attraction, role) and translate.
 *   3. Miss everywhere → call Claude in English, cache the English
 *      row, translate + cache the user-language row too.
 *
 * `X-Cache: HIT|TRANSLATED|MISS|MISS-TRANSLATED|MISS-NO-TRANS` for
 * monitoring.
 *
 * Why we generate fresh simulations instead of routing to the
 * /attraction page (the previous behaviour): many of these moments
 * (Library of Alexandria, Colossus of Rhodes, the Trojan Horse,
 * the Bastille, Pompeii at 79 AD) have no present-day attraction
 * to navigate to. The old "Details" button searched for the moment's
 * name and ended up on the wrong place — Beka caught
 * "Baghdad — The Mongol Sack" landing on a present-day Baghdad
 * museum page. The Time Machine is fundamentally a generation
 * surface, not a lookup surface.
 */
export const Route = createFileRoute("/api/time-machine")({
  server: {
    handlers: {
      POST: async ({ request }) => {
        const rawBody = await request.text();
        const key = extractKey(rawBody);
        if (!key) {
          return new Response(
            JSON.stringify({
              error: "Missing or invalid attractionId / role / language",
            }),
            { status: 400, headers: { "Content-Type": "application/json" } },
          );
        }
        const userLang = key.language;
        const wantsTranslation = !isEnglish(userLang);

        // 1. Direct cache hit.
        const cached = await getCachedTimeMachine({
          attractionId: key.attractionId,
          role: key.role,
          language: userLang,
        });
        if (cached !== null && hasBody(cached)) {
          return jsonResponse(cached, 200, "HIT");
        }

        // 2. Miss + non-English → English baseline + translate.
        if (wantsTranslation) {
          const cachedEn = await getCachedTimeMachine({
            attractionId: key.attractionId,
            role: key.role,
            language: "en",
          });
          if (cachedEn !== null && hasBody(cachedEn)) {
            const { payload: translated, translated: ok } = await translateTimeMachinePayload(
              cachedEn,
              userLang,
            );
            if (ok)
              await putCachedTimeMachine(
                { attractionId: key.attractionId, role: key.role, language: userLang },
                translated,
              );
            return jsonResponse(translated, 200, ok ? "TRANSLATED" : "TRANSLATE-FAILED");
          }
        }

        // 3. Cache miss everywhere — call Claude in English.
        const moment = ATTRACTIONS_BY_ID.get(key.attractionId);
        if (!moment) {
          return new Response(
            JSON.stringify({ error: `Unknown attractionId: ${key.attractionId}` }),
            { status: 400, headers: { "Content-Type": "application/json" } },
          );
        }
        try {
          const system = buildTimeMachineSystem();
          const user = buildTimeMachineUser({
            name: moment.name,
            year: moment.year,
            era: moment.era,
            country: moment.country,
            situation: moment.situation,
            role: key.role,
            language: "en",
          });
          // Haiku, not Sonnet — same Cloudflare 100s timeout reasoning
          // as /api/museum-highlights. The simulation body is long
          // (4-7 paragraphs of first-person prose) but Haiku at
          // ~150 tok/s comfortably fits inside the worker window. If
          // narrative quality regresses noticeably we can move this
          // back to Sonnet and rely on streaming, but that's a bigger
          // change. maxTokens 4096 is generous for a 6-minute read.
          const text = await callClaude({
            model: "claude-haiku-4-5",
            system,
            user,
            maxTokens: 4096,
            // Slightly higher temperature than the curatorial routes
            // — first-person fiction benefits from a touch more
            // looseness in voice.
            temperature: 0.85,
          });
          const parsed = parseClaudeJson(text);

          if (!parsed || !hasBody(parsed)) {
            const preview = typeof text === "string" ? text.slice(0, 200) : "(no text)";
            console.warn(
              "[time-machine] empty after parse",
              key.attractionId,
              key.role,
              "preview:",
              preview,
            );
            return jsonResponse(
              {
                error: "Upstream returned no usable simulation",
                debug: { moment: moment.name, role: key.role, textPreview: preview },
              },
              502,
              "MISS",
              "upstream-empty",
            );
          }

          await putCachedTimeMachine(
            { attractionId: key.attractionId, role: key.role, language: "en" },
            parsed,
          );

          if (wantsTranslation) {
            const { payload: translated, translated: ok } = await translateTimeMachinePayload(
              parsed,
              userLang,
            );
            if (ok)
              await putCachedTimeMachine(
                { attractionId: key.attractionId, role: key.role, language: userLang },
                translated,
              );
            return jsonResponse(translated, 200, ok ? "MISS-TRANSLATED" : "MISS-NO-TRANS");
          }

          return jsonResponse(parsed, 200, "MISS");
        } catch (err) {
          return new Response(
            JSON.stringify({
              error: err instanceof Error ? err.message : "Upstream failed",
            }),
            { status: 502, headers: { "Content-Type": "application/json" } },
          );
        }
      },
    },
  },
});

function extractKey(
  rawBody: string,
): { attractionId: string; role: string; language: string } | null {
  try {
    const obj = JSON.parse(rawBody) as Record<string, unknown>;
    const attractionId =
      (typeof obj.attractionId === "string" && obj.attractionId) ||
      (typeof obj.attraction_id === "string" && obj.attraction_id) ||
      "";
    const roleRaw =
      (typeof obj.role === "string" && obj.role) ||
      (typeof obj.character === "string" && obj.character) ||
      "";
    const language =
      (typeof obj.language === "string" && obj.language) ||
      (typeof obj.lang === "string" && obj.lang) ||
      "en";
    if (!attractionId.trim() || !roleRaw.trim()) return null;
    const role = roleRaw.trim().toLowerCase();
    // Reject unknown roles before paying Claude latency — the prompt
    // map only knows the 8 canonical values.
    if (!(TIME_MACHINE_ROLES as readonly string[]).includes(role)) return null;
    return {
      attractionId: attractionId.trim(),
      role,
      language: language.trim().toLowerCase(),
    };
  } catch {
    return null;
  }
}

function isEnglish(lang: string): boolean {
  return !lang || lang.toLowerCase().startsWith("en");
}

/**
 * Does this payload carry the narrative content we expect? `body`
 * is the long first-person prose — without it the rest of the JSON
 * is just metadata, not worth caching or returning.
 */
function hasBody(payload: unknown): boolean {
  if (!payload || typeof payload !== "object") return false;
  const obj = payload as Record<string, unknown>;
  return typeof obj.body === "string" && obj.body.trim().length > 50;
}

function jsonResponse(
  payload: unknown,
  status: number,
  cacheTag: string,
  reason?: string,
): Response {
  const headers: Record<string, string> = {
    "Content-Type": "application/json",
    "X-Cache": cacheTag,
  };
  if (reason) headers["X-Cache-Reason"] = reason;
  let body: string;
  if (typeof payload === "string") {
    body = payload;
  } else if (
    reason &&
    payload &&
    typeof payload === "object" &&
    !(payload as { reason?: unknown }).reason
  ) {
    body = JSON.stringify({ ...(payload as object), reason });
  } else {
    body = JSON.stringify(payload);
  }
  return new Response(body, { status, headers });
}
