/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimeMachineRouteImport } from './routes/time-machine'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as PlayerRouteImport } from './routes/player'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MapRouteImport } from './routes/map'
import { Route as LanguageRouteImport } from './routes/language'
import { Route as DestinationsRouteImport } from './routes/destinations'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DestinationSlugRouteImport } from './routes/destination.$slug'
import { Route as AttractionIdRouteImport } from './routes/attraction.$id'
import { Route as ApiTtsRouteImport } from './routes/api.tts'
import { Route as ApiTranslateRouteImport } from './routes/api.translate'
import { Route as ApiPhotoRouteImport } from './routes/api.photo'
import { Route as ApiGuideRouteImport } from './routes/api.guide'
import { Route as ApiAttractionsRouteImport } from './routes/api.attractions'

const TimeMachineRoute = TimeMachineRouteImport.update({
  id: '/time-machine',
  path: '/time-machine',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerRoute = PlayerRouteImport.update({
  id: '/player',
  path: '/player',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LanguageRoute = LanguageRouteImport.update({
  id: '/language',
  path: '/language',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsRoute = DestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationSlugRoute = DestinationSlugRouteImport.update({
  id: '/destination/$slug',
  path: '/destination/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AttractionIdRoute = AttractionIdRouteImport.update({
  id: '/attraction/$id',
  path: '/attraction/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranslateRoute = ApiTranslateRouteImport.update({
  id: '/api/translate',
  path: '/api/translate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPhotoRoute = ApiPhotoRouteImport.update({
  id: '/api/photo',
  path: '/api/photo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGuideRoute = ApiGuideRouteImport.update({
  id: '/api/guide',
  path: '/api/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAttractionsRoute = ApiAttractionsRouteImport.update({
  id: '/api/attractions',
  path: '/api/attractions',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/destinations': typeof DestinationsRoute
  '/language': typeof LanguageRoute
  '/map': typeof MapRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/player': typeof PlayerRoute
  '/results': typeof ResultsRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/time-machine': typeof TimeMachineRoute
  '/api/attractions': typeof ApiAttractionsRoute
  '/api/guide': typeof ApiGuideRoute
  '/api/photo': typeof ApiPhotoRoute
  '/api/translate': typeof ApiTranslateRoute
  '/api/tts': typeof ApiTtsRoute
  '/attraction/$id': typeof AttractionIdRoute
  '/destination/$slug': typeof DestinationSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/destinations': typeof DestinationsRoute
  '/language': typeof LanguageRoute
  '/map': typeof MapRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/player': typeof PlayerRoute
  '/results': typeof ResultsRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/time-machine': typeof TimeMachineRoute
  '/api/attractions': typeof ApiAttractionsRoute
  '/api/guide': typeof ApiGuideRoute
  '/api/photo': typeof ApiPhotoRoute
  '/api/translate': typeof ApiTranslateRoute
  '/api/tts': typeof ApiTtsRoute
  '/attraction/$id': typeof AttractionIdRoute
  '/destination/$slug': typeof DestinationSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/destinations': typeof DestinationsRoute
  '/language': typeof LanguageRoute
  '/map': typeof MapRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/player': typeof PlayerRoute
  '/results': typeof ResultsRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/time-machine': typeof TimeMachineRoute
  '/api/attractions': typeof ApiAttractionsRoute
  '/api/guide': typeof ApiGuideRoute
  '/api/photo': typeof ApiPhotoRoute
  '/api/translate': typeof ApiTranslateRoute
  '/api/tts': typeof ApiTtsRoute
  '/attraction/$id': typeof AttractionIdRoute
  '/destination/$slug': typeof DestinationSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/destinations'
    | '/language'
    | '/map'
    | '/notifications'
    | '/onboarding'
    | '/player'
    | '/results'
    | '/saved'
    | '/settings'
    | '/time-machine'
    | '/api/attractions'
    | '/api/guide'
    | '/api/photo'
    | '/api/translate'
    | '/api/tts'
    | '/attraction/$id'
    | '/destination/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/destinations'
    | '/language'
    | '/map'
    | '/notifications'
    | '/onboarding'
    | '/player'
    | '/results'
    | '/saved'
    | '/settings'
    | '/time-machine'
    | '/api/attractions'
    | '/api/guide'
    | '/api/photo'
    | '/api/translate'
    | '/api/tts'
    | '/attraction/$id'
    | '/destination/$slug'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/destinations'
    | '/language'
    | '/map'
    | '/notifications'
    | '/onboarding'
    | '/player'
    | '/results'
    | '/saved'
    | '/settings'
    | '/time-machine'
    | '/api/attractions'
    | '/api/guide'
    | '/api/photo'
    | '/api/translate'
    | '/api/tts'
    | '/attraction/$id'
    | '/destination/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DestinationsRoute: typeof DestinationsRoute
  LanguageRoute: typeof LanguageRoute
  MapRoute: typeof MapRoute
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  PlayerRoute: typeof PlayerRoute
  ResultsRoute: typeof ResultsRoute
  SavedRoute: typeof SavedRoute
  SettingsRoute: typeof SettingsRoute
  TimeMachineRoute: typeof TimeMachineRoute
  ApiAttractionsRoute: typeof ApiAttractionsRoute
  ApiGuideRoute: typeof ApiGuideRoute
  ApiPhotoRoute: typeof ApiPhotoRoute
  ApiTranslateRoute: typeof ApiTranslateRoute
  ApiTtsRoute: typeof ApiTtsRoute
  AttractionIdRoute: typeof AttractionIdRoute
  DestinationSlugRoute: typeof DestinationSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/time-machine': {
      id: '/time-machine'
      path: '/time-machine'
      fullPath: '/time-machine'
      preLoaderRoute: typeof TimeMachineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player': {
      id: '/player'
      path: '/player'
      fullPath: '/player'
      preLoaderRoute: typeof PlayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/language': {
      id: '/language'
      path: '/language'
      fullPath: '/language'
      preLoaderRoute: typeof LanguageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations': {
      id: '/destinations'
      path: '/destinations'
      fullPath: '/destinations'
      preLoaderRoute: typeof DestinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destination/$slug': {
      id: '/destination/$slug'
      path: '/destination/$slug'
      fullPath: '/destination/$slug'
      preLoaderRoute: typeof DestinationSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attraction/$id': {
      id: '/attraction/$id'
      path: '/attraction/$id'
      fullPath: '/attraction/$id'
      preLoaderRoute: typeof AttractionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/translate': {
      id: '/api/translate'
      path: '/api/translate'
      fullPath: '/api/translate'
      preLoaderRoute: typeof ApiTranslateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/photo': {
      id: '/api/photo'
      path: '/api/photo'
      fullPath: '/api/photo'
      preLoaderRoute: typeof ApiPhotoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/guide': {
      id: '/api/guide'
      path: '/api/guide'
      fullPath: '/api/guide'
      preLoaderRoute: typeof ApiGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/attractions': {
      id: '/api/attractions'
      path: '/api/attractions'
      fullPath: '/api/attractions'
      preLoaderRoute: typeof ApiAttractionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DestinationsRoute: DestinationsRoute,
  LanguageRoute: LanguageRoute,
  MapRoute: MapRoute,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  PlayerRoute: PlayerRoute,
  ResultsRoute: ResultsRoute,
  SavedRoute: SavedRoute,
  SettingsRoute: SettingsRoute,
  TimeMachineRoute: TimeMachineRoute,
  ApiAttractionsRoute: ApiAttractionsRoute,
  ApiGuideRoute: ApiGuideRoute,
  ApiPhotoRoute: ApiPhotoRoute,
  ApiTranslateRoute: ApiTranslateRoute,
  ApiTtsRoute: ApiTtsRoute,
  AttractionIdRoute: AttractionIdRoute,
  DestinationSlugRoute: DestinationSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
