// This file is automatically generated. Do not edit it directly.
//
// HARDCODED OVERRIDE (Beka 2026-06-13) — Lovable's Supabase integration
// kept reverting .env back to the OLD pymoatqlaochyruyytbj project on
// every Publish, so Google sign-in stayed broken even after pushing
// the new values. The fix is to bypass .env entirely and pin the
// active project (dwyajguhgyjbgkpzjaln, "Lokali") directly in source.
//
// The anon/publishable key is meant to be public — it's already
// shipped in every browser bundle when read from VITE_* env vars, so
// embedding it in the source has no security cost. Replace the values
// below if the project is ever rotated again (and make sure Lovable
// support has fixed the integration before relying on .env again).

import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://dwyajguhgyjbgkpzjaln.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR3eWFqZ3VoZ3lqYmdrcHpqYWxuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc4MzMzNjksImV4cCI6MjA5MzQwOTM2OX0.MoTEVP6ktmgwDm18NonHxudM3LyFyu5kdkHtX8jSkLE";

function createSupabaseClient() {
  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
