// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function createSupabaseAdminClient() {
  // Prefer the EXTERNAL_* env vars over SUPABASE_*. Background
  // (Beka 2026-06-21 — same root cause we hit on the client side):
  // Lovable's Supabase integration auto-rewrites SUPABASE_URL +
  // SUPABASE_SERVICE_ROLE_KEY on every Publish, pointing them at
  // Lovable's own provisioned project (pymoatqlaochyruyytbj). The
  // client.ts is hardcoded against Beka's project
  // (dwyajguhgyjbgkpzjaln), so tokens issued client-side cannot be
  // verified by an admin client built from the auto-managed env vars
  // — every /api/account/delete attempt 401'd with "Invalid token"
  // because the two projects have different JWT signing keys.
  // Lovable explicitly leaves non-SUPABASE_-prefixed secrets alone,
  // so we use the same EXTERNAL_* names sharedCache.server.ts uses
  // and fall back to the auto-managed vars only when the EXTERNAL
  // pair isn't set (keeps legacy deployments working).
  const SUPABASE_URL =
    process.env.EXTERNAL_SUPABASE_URL ?? process.env.SUPABASE_URL;
  const SUPABASE_SERVICE_ROLE_KEY =
    process.env.EXTERNAL_SUPABASE_SERVICE_ROLE_KEY ??
    process.env.SUPABASE_SERVICE_ROLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
    throw new Error(
      "Missing Supabase server environment variables. Set either " +
        "EXTERNAL_SUPABASE_URL + EXTERNAL_SUPABASE_SERVICE_ROLE_KEY " +
        "(preferred, Lovable won't auto-manage them) or the legacy " +
        "SUPABASE_URL + SUPABASE_SERVICE_ROLE_KEY pair.",
    );
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    },
  });
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

// Server-side Supabase client with service role - bypasses RLS
// SECURITY: Only use this for trusted server-side operations, never expose to client code
// Import like: import { supabaseAdmin } from "@/integrations/supabase/client.server";
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});
